version: "3"
services:
  # cumulative-trend-service:
  #   build:
  #     context: "./server/cumulative-trend-service/"
  #   depends_on:
  #     - cumulative-trend-db
  #   container_name: cumulative-trend-service
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./server/cumulative-trend-service:/usr/src/app

  cumulative-trend-db:
    container_name: cumulative-trend-db-server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cumulative-trend-db
    image: postgres:latest
    ports:
      - "3005:5432"
    volumes:
      - cumulativeDB-data:/var/lib/postgresql/data/

  daily-trend-service:
    build:
      context: "./server/daily-trend-service/"
    depends_on:
      - daily-trend-db
    container_name: daily-trend-service
    ports:
      - "3002:3002"
    volumes:
      - ./server/daily-trend-service:/usr/src/app

  daily-trend-db:
    container_name: daily-trend-db-server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=daily-trend-db
    image: postgres:latest
    ports:
      - "3006:5432"
    volumes:
      - dailyDB-data:/var/lib/postgresql/data/

  national-total-service:
    build:
      context: "./server/national-total-service/"
    depends_on:
      - national-total-db
    container_name: national-total-service
    ports:
      - "3003:3003"
    volumes:
      - ./server/national-total-service:/usr/src/app

  national-total-db:
    container_name: national-total-db-server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=national-total-db
    image: postgres:latest
    ports:
      - "3007:5432"
    volumes:
      - nationalDB-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped

volumes:
  cumulativeDB-data:
  dailyDB-data:
  nationalDB-data:
