version: "3"
services:
  cumulative-trend-service:
    build:
      context: "./server/cumulative-trend-service/"
    depends_on:
      - cumulative-trend-db
    ports:
      - "3001:3001"
    volumes:
      - ./server/cumulative-trend-service:/usr/src/app

  cumulative-trend-db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:latest
    ports:
      - "3005:5432"
    volumes:
      - cumulativeDB-data:/var/lib/postgresql/data/

  daily-trend-service:
    build:
      context: "./server/daily-trend-service/"
    depends_on:
      - daily-trend-db
    ports:
      - "3002:3002"
    volumes:
      - ./server/daily-trend-service:/usr/src/app

  daily-trend-db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:latest
    ports:
      - "3006:5432"
    volumes:
      - dailyDB-data:/var/lib/postgresql/data/

  national-total-service:
    build:
      context: "./server/national-total-service/"
    depends_on:
      - national-total-db
    ports:
      - "3003:3003"
    volumes:
      - ./server/national-total-service:/usr/src/app

  national-total-db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:latest
    ports:
      - "3007:5432"
    volumes:
      - nationalDB-data:/var/lib/postgresql/data/

volumes:
  cumulativeDB-data:
  dailyDB-data:
  nationalDB-data:
