AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: "Deploys RDS databases for multiple microservices"
Parameters:
  StackName:
    Type: String
    Default: <VPC STACK NAME>
    Description: The name of the VPC stack that you created. Necessary
      to locate and reference resources created by that stack.
  CumulativeDBName:
    Description: Cumulative database name
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  CumulativeDBUser:
    NoEcho: "true"
    Description: The admin account username of Cumulative database
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  CumulativeDBPassword:
    NoEcho: "true"
    Description: The admin account password of Cumulative database
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DailyDBName:
    Description: Daily database name
    Type: String
    MinLength: "1"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MaxLength: "64"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DailyDBUser:
    NoEcho: "true"
    Description: The admin account username of Daily database
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DailyDBPassword:
    NoEcho: "true"
    Description: The admin account password of Daily database
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  NationalDBName:
    Description: National database name
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  NationalDBUser:
    NoEcho: "true"
    Description: The admin account username of National database
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  NationalDBPassword:
    NoEcho: "true"
    Description: The admin account password of National database
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "RDS Subnet Group"
      DBSubnetGroupName: RDSSubnetGroup
      SubnetIds:
        - Fn::ImportValue: !Join [":", [!Ref "StackName", "PublicSubnetOne"]]
        - Fn::ImportValue: !Join [":", [!Ref "StackName", "PublicSubnetTwo"]]

  CumulativeDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref "CumulativeDBName"
      AllocatedStorage: "5"
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 11.7
      MasterUsername: !Ref "CumulativeDBUser"
      MasterUserPassword: !Ref "CumulativeDBPassword"
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Join [":", [!Ref "StackName", "EcsHostSecurityGroup"]]

  DailyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref "DailyDBName"
      AllocatedStorage: "5"
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 11.7
      MasterUsername: !Ref "DailyDBUser"
      MasterUserPassword: !Ref "DailyDBPassword"
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Join [":", [!Ref "StackName", "EcsHostSecurityGroup"]]

  NationalDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref "NationalDBName"
      AllocatedStorage: "5"
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 11.7
      MasterUsername: !Ref "NationalDBUser"
      MasterUserPassword: !Ref "NationalDBPassword"
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Join [":", [!Ref "StackName", "EcsHostSecurityGroup"]]

Outputs:
  CumulativeJDBCURI:
    Description: JDBC connection string for Cumulative database
    Value:
      !Join [
        "",
        [
          "postgres://",
          !Ref CumulativeDBUser,
          ":",
          !Ref CumulativeDBPassword,
          "@",
          !GetAtt [CumulativeDB, Endpoint.Address],
          ":5432/",
          !Ref "CumulativeDBName",
        ],
      ]
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "CumulativeDBURI"]]
  DailyJDBCURI:
    Description: JDBC connection string for Daily database
    Value:
      !Join [
        "",
        [
          "postgres://",
          !Ref DailyDBUser,
          ":",
          !Ref DailyDBPassword,
          "@",
          !GetAtt [DailyDB, Endpoint.Address],
          ":5432/",
          !Ref "DailyDBName",
        ],
      ]
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DailyJDBCURI"]]
  NationalJDBCURI:
    Description: JDBC connection string for National database
    Value:
      !Join [
        "",
        [
          "postgres://",
          !Ref NationalDBUser,
          ":",
          !Ref NationalDBPassword,
          "@",
          !GetAtt [NationalDB, Endpoint.Address],
          ":5432/",
          !Ref "NationalDBName",
        ],
      ]
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "NationalJDBCURI"]]
